### ISSUE TITLE
Check redirects to alternative domains

### ISSUE THREAD

**Issue by erciccione** [firoorg/firo-site#266]
The main address is `https://firo.org`. Other domains like `https://www.firo.org` an `http://www.firo.org` don't seem to redirect to the correct domain. This results in domains being indexed twice, at the expenses of SEO score. 301 redirects should be set up, pointing to the main domain `https://firo.org`

**Comment by justanwar** [comment]
Updated, could you verify?

**Comment by erciccione** [comment]
Looks good now. Thanks @justanwar.
