### ISSUE TITLE
Added new coin-swapping services (SwapSwop)

### ISSUE THREAD

**Issue by antonegorov** [firoorg/firo-site#58]
Hello,
Added an exchanger that exchanges FIRO. The service is more than 1 year old. PR attached #57 

Thanks.

**Comment by rehrar** [comment]
Merged. Thanks.

**Comment by antonegorov** [comment]
Hello.

Thank you for your attention.

I have a question: Have the changes been uploaded to the site? Couldn't find an update on [site](https://firo.org/get-firo/buy-firo/#coinswap)
